In [1]:
# importing relevant libraries that will help
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline

In [99]:
df = pd.read_csv('energydata_complete.csv')
df

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [91]:
x = df['T2'].values.reshape(-1,1)
y = df['T6'].values.reshape(-1,1)

In [94]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [95]:
regressor = LinearRegression()  
regressor.fit(x_train, y_train) #training the algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [96]:
y_pred = regressor.predict(x_test)
df = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
df

         Actual  Predicted
0      1.198571   2.155789
1      2.530000  10.011161
2     -0.266667   1.873916
3     11.160000  15.796987
4     -0.733333  -0.729706
...         ...        ...
5916   0.100000   9.803464
5917   8.660000   5.360247
5918   9.600000   4.247588
5919  13.195714   8.698223
5920  12.500000   4.989360

[5921 rows x 2 columns]

In [97]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, y_pred)
print('the r2_score is', round(r2_score, 2))

the r2_score is 0.64

In [100]:
from sklearn.preprocessing import MinMaxScaler

#Firstly, we drop the columns date and lights

df.drop(['date', 'lights'], axis = 1, inplace = True)

In [101]:
#Secondly, we normalise our dataset to a common scale using the min max scaler
scaler = MinMaxScaler()
normalised_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
features_df = normalised_df.drop(columns=[ 'Appliances' ])
target = normalised_df[ 'Appliances' ]

In [102]:
#Now, we split our dataset into the training and testing dataset. Recall that we had earlier segmented the features and target variables.

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_df, target,
test_size= 0.3 , random_state= 42 )

In [103]:
regressor = LinearRegression()  
regressor.fit(x_train, y_train) #training the algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [104]:
predicted_value = regressor.predict(x_test)
predicted_value

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

In [108]:
# Question 13 (MAE)
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_value)
print('the MAE is ', round(mae, 2))

the MAE is  0.05

In [109]:
# Question 14 (RSS)
import numpy as np
y_test6=np.array(y_test)
predicted_values6= np.array(predicted_value)
rss = np.sum(np.square(y_test6-predicted_values6))
print('the RSS is ', round(rss,2))

the RSS is  45.35

In [110]:
# Question 15 (RMSE)
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_value))
print('the RMSE is ', round(rmse, 3))

the RMSE is  0.088

In [111]:
# Question 16 (Coefficient of Determination)
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predicted_value)
print('the Coefficient of Determination is ',round(r2_score, 2))

the Coefficient of Determination is  0.15

In [112]:
#To retrieve the intercept:
print(regressor.intercept_)
#For retrieving the slope:
print(regressor.coef_)

0.15290295882253055
[-0.00328105  0.5535466  -0.23617792 -0.45669795  0.29062714  0.09604827
  0.028981    0.02638578 -0.01565684  0.01600579  0.23642491  0.03804865
  0.01031878 -0.04461364  0.10199505 -0.15759548 -0.18994077 -0.03980032
 -0.32185967  0.00683933 -0.07767065  0.02918313  0.01230661  0.11775773
  0.0007701   0.0007701 ]

In [113]:
# Ridge Regression
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha= 0.5 )
ridge_reg.fit(x_train, y_train)

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [114]:
# Feature Selection and Lasso Regression
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha= 0.001 )
lasso_reg.fit(x_train, y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [135]:
#comparing the effects of regularisation
def get_weights_df(model, feat, col_name) :
#this function returns the weight of every feature
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = [ 'Features' , col_name]
    weights_df[col_name].round(3)
    return weights_df

linear_model_weights = get_weights_df(regressor, x_train, 'Linear_Model_Weight' )
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight' )
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight' )

final_weights = pd.merge(linear_model_weights, ridge_weights_df, on= 'Features' )
final_weights = pd.merge(final_weights, lasso_weights_df, on= 'Features' )

final_weights

       Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456698     -0.411071     -0.000000
1         T_out            -0.321860     -0.262172      0.000000
2            T2            -0.236178     -0.201397      0.000000
3            T9            -0.189941     -0.188916     -0.000000
4          RH_8            -0.157595     -0.156830     -0.000110
5        RH_out            -0.077671     -0.054724     -0.049557
6          RH_7            -0.044614     -0.045977     -0.000000
7          RH_9            -0.039800     -0.041367     -0.000000
8            T5            -0.015657     -0.019853     -0.000000
9            T1            -0.003281     -0.018406      0.000000
10          rv1             0.000770      0.000748     -0.000000
11          rv2             0.000770      0.000748     -0.000000
12  Press_mm_hg             0.006839      0.006584     -0.000000
13           T7             0.010319      0.010098     -0.000000
14   Visibility             0.012307      0.012076      0.000000
15         RH_5             0.016006      0.016152      0.000000
16         RH_4             0.026386      0.024579      0.000000
17           T4             0.028981      0.027384     -0.000000
18    Windspeed             0.029183      0.030268      0.002912
19         RH_6             0.038049      0.035519     -0.000000
20         RH_3             0.096048      0.095135      0.000000
21           T8             0.101995      0.101028      0.000000
22    Tdewpoint             0.117758      0.083128      0.000000
23           T6             0.236425      0.217292      0.000000
24           T3             0.290627      0.288087      0.000000
25         RH_1             0.553547      0.519525      0.017880

In [59]:
print(final_weights.loc[:, 'Linear_Model_Weight'].min())


print(final_weights.loc[:, 'Linear_Model_Weight'].max())

-0.45669794833849997
0.5535465998386386

In [117]:
b = final_weights['Linear_Model_Weight'].groupby(final_weights['Features'])
print('the minimum value is ', b.sum().idxmin())
print('the maximum value is ', b.sum().idxmax())

the minimum value is  RH_2
the maximum value is  RH_1

In [121]:
# Ridge Regression
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha= 0.4 )
ridge_reg.fit(x_train, y_train)

#comparing the effects of regularisation
def get_weights_df(model, feat, col_name) :
#this function returns the weight of every feature
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = [ 'Features' , col_name]
    weights_df[col_name].round(3)
    return weights_df

linear_model_weights = get_weights_df(regressor, x_train, 'Linear_Model_Weight' )
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight' )

final_weights = pd.merge(linear_model_weights, ridge_weights_df, on= 'Features' )


final_weights

       Features  Linear_Model_Weight  Ridge_Weight
0          RH_2            -0.456698     -0.411071
1         T_out            -0.321860     -0.262172
2            T2            -0.236178     -0.201397
3            T9            -0.189941     -0.188916
4          RH_8            -0.157595     -0.156830
5        RH_out            -0.077671     -0.054724
6          RH_7            -0.044614     -0.045977
7          RH_9            -0.039800     -0.041367
8            T5            -0.015657     -0.019853
9            T1            -0.003281     -0.018406
10          rv1             0.000770      0.000748
11          rv2             0.000770      0.000748
12  Press_mm_hg             0.006839      0.006584
13           T7             0.010319      0.010098
14   Visibility             0.012307      0.012076
15         RH_5             0.016006      0.016152
16         RH_4             0.026386      0.024579
17           T4             0.028981      0.027384
18    Windspeed             0.029183      0.030268
19         RH_6             0.038049      0.035519
20         RH_3             0.096048      0.095135
21           T8             0.101995      0.101028
22    Tdewpoint             0.117758      0.083128
23           T6             0.236425      0.217292
24           T3             0.290627      0.288087
25         RH_1             0.553547      0.519525

In [120]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_value))
round(rmse, 3)

0.088

In [136]:
# Question 19
# Firstly, we group the otline the lasso_weight after training
b = final_weights['Lasso_weight'].groupby(final_weights['Features'])
b.sum()

Features
Press_mm_hg    0.000000
RH_1           0.017880
RH_2           0.000000
RH_3           0.000000
RH_4           0.000000
RH_5           0.000000
RH_6           0.000000
RH_7           0.000000
RH_8          -0.000110
RH_9           0.000000
RH_out        -0.049557
T1             0.000000
T2             0.000000
T3             0.000000
T4             0.000000
T5             0.000000
T6             0.000000
T7             0.000000
T8             0.000000
T9             0.000000
T_out          0.000000
Tdewpoint      0.000000
Visibility     0.000000
Windspeed      0.002912
rv1            0.000000
rv2            0.000000
Name: Lasso_weight, dtype: float64

In [ ]:
df.drop(['RH_2'], axis = 1, inplace = True)
scaler = MinMaxScaler()
normalised_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
features_df = normalised_df(columns=[ 'RH_1','RH_8','RH_out', 'Windspeed' ])
target = normalised_df[ 'Appliances' ]
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_df, target,
test_size= 0.3 , random_state= 42 )
regressor = LinearRegression()  
regressor.fit(x_train, y_train) #training the algorithm